#!/bin/bash
s=0; for ((i=0;i<${#WATER};i++)); do s=$((s*5+${#w})); done; for ((i=0;i<${#STIR};i++)); do s=$((s*5+${#s})); done; n=$s; o=""; while ((n)); do o="${bestchol:n%10:1}$o"; n=$((n/10)); done; echo $o
