#!/usr/bin/env bash
# Displays Best School 10 times
i=l
while [ "$i" -le 10 ]
do
        if [ "$i" -eq 9 ]
        then
                echo "Best School"
                echo "Hi"
        else
                echo "Best School"
        fi
        i=$(( i + l ))
done
