#!/usr/bin/env bash
#Add a route with query parameters

##
# You should look at the following URL's in order to grasp a solid understanding
# of Nginx configuration files in order to fully unleash the power of Nginx.
# http://wiki.nginx.org/Pitfalls
# http://wiki.nginx.org/QuickStart
# http://wiki.nginx.org/Configuration
#
# Generally, you will want to move this file somewhere, and start with a clean
# file but keep this around for reference. Or just disable in sites-enabled.
#
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
##

# Default server configuration
#
server {
        listen 80 default_server;
        error_page 404 /404.html;
        location = /404.html {
                root /var/www/html;
                internal;
        }
        listen [::]:80 default_server;

	#IP
	server_name 54.198.55.96;

	#Custom
	add_header X-Served-By 232782-web-01;


	# Serve /airbnb-onepage/ route on AirBnB_clone_v3
        location = /airbnb-onepage/  {
            proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
	}

        # Serve /nimber_odd_or_even/ route on AirBnB_clone_v2
        location ~ /airbnb-dynamic/number_odd_or_even/(\d+)$ {
            proxy_pass http://127.0.0.1:5001/number_odd_or_even/$1;
        }

        

}
