#!/usr/bin/env bash
# Serve your AirBnB clone

server {
        listen 80 default_server;
        error_page 404 /404.html;
        location = /404.html {
                root /var/www/html;
                internal;
        }
        listen [::]:80 default_server;

        #IP
        server_name 54.198.55.96;

        index index.html index.htm index.nginx-debian.html;
        rewrite ^/redirect_me https://github.com/Musawenkosistar permanent;

        #Custom
        add_header X-Served-By 232782-web-01;

        error_page 404 /404.html;

        # Serve /airbnb-onepage/ route on AirBnB_clone_v3
        location = /airbnb-onepage/  {
            proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
        }

        # Serve /nimber_odd_or_even/ route on AirBnB_clone_v2
        location ~ /airbnb-dynamic/number_odd_or_even/(\d+)$ {
            proxy_pass http://127.0.0.1:5001/number_odd_or_even/$1;
        }


        location /api/ {
                include proxy_params;
                proxy_pass http://0.0.0.0:5002/api/;
        }

        location / {
                try_files $uri $uri/ =404;
        }

}
